// The authorisation point for every media upload the admin performs.
//
// This function never sees the file's bytes — only its declared content type
// and size — and never returns an S3 credential to the browser. It returns a
// URL, presigned for exactly one PUT to exactly one object, that expires in
// five minutes. Everything that decides whether an upload is allowed at all
// happens here, before that URL is ever handed out:
//
//   - WHO is calling is established from the database, not the JWT. A caller
//     may present a token carrying whatever claims it likes; this function
//     asks Supabase Auth who that token actually belongs to (getUser), then
//     asks Postgres — with the service-role key, bypassing RLS — what that
//     user's profiles.role is. A role claimed inside the token itself is
//     never consulted.
//   - WHERE the file lands is chosen here, not by the caller. The storage
//     key is a fixed prefix, a fresh UUID, and an extension derived from the
//     (allowlisted) content type — never from the client-supplied file name.
//     A caller who could choose the key could overwrite another object or
//     escape the prefix; generating it server-side removes that choice
//     entirely.
//   - Missing S3 configuration is a 500, never a fallback to an unsigned
//     URL. An admin tool with no working upload path is a bug; an admin
//     tool that silently uploads without authorisation is a breach.

import { createClient } from 'npm:@supabase/supabase-js@2.111.0';
import { presignPut } from '../_shared/s3-presign.js';

const allowedOrigins = (Deno.env.get('ALLOWED_ORIGINS') ?? '')
  .split(',')
  .map((origin) => origin.trim())
  .filter(Boolean);

// The request body is three short fields (a MIME type, a byte count, a file
// name) — nothing legitimate is anywhere near this size. Generous enough
// that an unusually long file name never trips it, tight enough that it is
// not a meaningful denial-of-service surface.
const MAX_BODY_BYTES = 8 * 1024;

// Configurable so a real deployment can tighten or loosen it without a code
// change, same pattern as submit-inquiry's INQUIRY_RATE_LIMIT. Images are
// resized and re-encoded to WebP in the browser before this is ever called
// (see the Phase 3 design doc, section 6.1), so a legitimate upload sits far
// under this; it exists to bound how much an admin session can ever put in
// one object, not to size for the common case.
const DEFAULT_MAX_UPLOAD_BYTES = 15 * 1024 * 1024;

// Every key generated by this function falls under this prefix, regardless
// of what the caller asked for — see generateStoragePath below.
const STORAGE_KEY_PREFIX = 'uploads';

// The only content types this studio's site ever renders as an image.
// Extensions are derived from this map, never from the caller's file name —
// see the module comment above for why that matters.
const ALLOWED_CONTENT_TYPES = {
  'image/jpeg': 'jpg',
  'image/png': 'png',
  'image/webp': 'webp',
};

const PRESIGN_EXPIRES_IN_SECONDS = 300;

function corsHeaders(requestOrigin) {
  // This controls which origins a BROWSER will let its own JavaScript read
  // the response from — nothing more. It is not a write control: request
  // handling below still runs for a request carrying any Origin header at
  // all (or none), because CORS is enforced by the browser refusing to hand
  // the response to script, not by this server refusing the request. A
  // non-browser client — curl, a script, a bot — ignores CORS entirely and
  // reads the response regardless of what this function sets. The only
  // actual controls on who may obtain a signed upload URL are the JWT check
  // and the admin-role check below.
  //
  // Unset means local development, where the dev server's origin varies.
  // Phase 4's deploy checklist sets ALLOWED_ORIGINS to the real domain.
  const allowOrigin = allowedOrigins.length === 0
    ? '*'
    : (allowedOrigins.includes(requestOrigin) ? requestOrigin : allowedOrigins[0]);

  return {
    'Access-Control-Allow-Origin': allowOrigin,
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    Vary: 'Origin',
  };
}

function json(status, body, requestOrigin, extraHeaders = {}) {
  return new Response(JSON.stringify(body), {
    status,
    // extraHeaders spread first so a caller can never displace the CORS
    // headers or the content type — see submit-inquiry's identical json()
    // for the failure mode this ordering avoids.
    headers: {
      ...extraHeaders,
      ...corsHeaders(requestOrigin),
      'Content-Type': 'application/json',
    },
  });
}

// Reads the body up to maxBytes, discarding anything beyond that rather than
// retaining it, so memory use stays bounded no matter how large the sender
// claims — or attempts — to send. Identical in shape to submit-inquiry's
// readBodyWithLimit; see that function's comment for why `await req.text()`
// does not give the same guarantee, and why this drains to completion
// instead of cancelling the stream outright once over the cap.
async function readBodyWithLimit(req, maxBytes) {
  if (!req.body) {
    return { text: '', tooLarge: false };
  }

  const reader = req.body.getReader();
  const chunks = [];
  let total = 0;
  let tooLarge = false;

  for (;;) {
    const { done, value } = await reader.read();
    if (done) {
      break;
    }
    if (tooLarge) {
      continue;
    }
    total += value.byteLength;
    if (total > maxBytes) {
      tooLarge = true;
      chunks.length = 0;
      continue;
    }
    chunks.push(value);
  }

  if (tooLarge) {
    return { text: '', tooLarge: true };
  }

  const combined = new Uint8Array(total);
  let offset = 0;
  for (const chunk of chunks) {
    combined.set(chunk, offset);
    offset += chunk.byteLength;
  }
  return { text: new TextDecoder().decode(combined), tooLarge: false };
}

// Reads the body to completion, discarding every chunk, so the connection is
// left fully drained before a response is written on it. See
// readBodyWithLimit above (and submit-inquiry's identical drainBody) for why
// responding before the body is consumed can leave the response unable to
// reach the caller at all.
async function drainBody(req) {
  if (!req.body) {
    return;
  }
  const reader = req.body.getReader();
  try {
    for (;;) {
      const { done } = await reader.read();
      if (done) {
        break;
      }
    }
  } catch {
    // The connection is being rejected anyway; nothing more to do if the
    // stream itself errors while draining it.
  }
}

// A fresh UUID under a fixed prefix, extension taken from the (already
// allowlisted) content type. The caller's file name never participates —
// nothing here reads `fileName` at all — so a value like `../../evil.png`
// has no path through this function to the returned storagePath.
function generateStoragePath(contentType) {
  const extension = ALLOWED_CONTENT_TYPES[contentType];
  return `${STORAGE_KEY_PREFIX}/${crypto.randomUUID()}.${extension}`;
}

function readMaxUploadBytes() {
  const raw = Deno.env.get('MAX_UPLOAD_BYTES');
  if (raw === undefined || raw === '') {
    return DEFAULT_MAX_UPLOAD_BYTES;
  }
  const parsed = Number(raw);
  if (!Number.isFinite(parsed) || parsed <= 0) {
    console.error(
      `sign-upload: MAX_UPLOAD_BYTES=${raw} is not a positive number, using default of ${DEFAULT_MAX_UPLOAD_BYTES}`,
    );
    return DEFAULT_MAX_UPLOAD_BYTES;
  }
  return parsed;
}

Deno.serve(async (req) => {
  const origin = req.headers.get('origin') ?? '';

  if (req.method === 'OPTIONS') {
    return new Response(null, { status: 204, headers: corsHeaders(origin) });
  }

  if (req.method !== 'POST') {
    return json(405, { ok: false, error: 'METHOD_NOT_ALLOWED' }, origin);
  }

  // Body size guard. Runs before anything else — including auth — for the
  // same reason submit-inquiry's does: nothing after this point may move
  // ahead of it, so an oversized body can never slip past whatever check
  // happens to run first.
  //
  // content-length is a cheap fast path, not the control: it can be absent
  // under chunked transfer encoding, or simply wrong. The bounded stream
  // read below is what actually enforces the cap. A body this far over the
  // limit cannot be the small JSON object this endpoint expects, so it is
  // reported as MALFORMED_REQUEST rather than inventing a new status code
  // outside the table this function documents.
  const contentLengthHeader = req.headers.get('content-length');
  const contentLength = contentLengthHeader === null ? NaN : Number(contentLengthHeader);
  if (Number.isFinite(contentLength) && contentLength > MAX_BODY_BYTES) {
    await drainBody(req);
    return json(400, { ok: false, error: 'MALFORMED_REQUEST' }, origin);
  }

  const body = await readBodyWithLimit(req, MAX_BODY_BYTES);
  if (body.tooLarge) {
    return json(400, { ok: false, error: 'MALFORMED_REQUEST' }, origin);
  }

  let payload;
  try {
    payload = JSON.parse(body.text);
  } catch {
    return json(400, { ok: false, error: 'MALFORMED_REQUEST' }, origin);
  }

  const { contentType, byteSize, fileName } = payload ?? {};

  if (
    typeof contentType !== 'string' || contentType === '' ||
    typeof byteSize !== 'number' || !Number.isFinite(byteSize) || byteSize <= 0 ||
    typeof fileName !== 'string' || fileName === ''
  ) {
    return json(400, { ok: false, error: 'MALFORMED_REQUEST' }, origin);
  }

  // WHO is calling: verified against Supabase Auth from the caller's own
  // token, never assumed from anything the token merely claims. A missing
  // or invalid Authorization header — no session, an expired token, a
  // malformed one — resolves to the same UNAUTHENTICATED response as a
  // token Auth flatly rejects; a caller with no valid session at all learns
  // nothing more from this endpoint than one whose token failed
  // verification.
  const authHeader = req.headers.get('Authorization') ?? req.headers.get('authorization');
  if (!authHeader) {
    return json(401, { ok: false, error: 'UNAUTHENTICATED' }, origin);
  }

  const supabaseUrl = Deno.env.get('SUPABASE_URL');
  const anonKey = Deno.env.get('SUPABASE_ANON_KEY');
  const serviceRoleKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');

  const callerClient = createClient(supabaseUrl, anonKey, {
    global: { headers: { Authorization: authHeader } },
    auth: { persistSession: false },
  });

  const { data: userData, error: userError } = await callerClient.auth.getUser();
  if (userError || !userData?.user) {
    return json(401, { ok: false, error: 'UNAUTHENTICATED' }, origin);
  }

  // WHAT they may do: read directly from profiles with the service-role
  // key, bypassing RLS entirely, rather than trusting any role claim the
  // token itself might carry. See the module comment for why this
  // distinction is the whole point of this function.
  const db = createClient(supabaseUrl, serviceRoleKey, {
    auth: { persistSession: false },
  });

  const { data: profile, error: profileError } = await db
    .from('profiles')
    .select('role')
    .eq('user_id', userData.user.id)
    .maybeSingle();

  if (profileError) {
    console.error('sign-upload: profile lookup failed', profileError.message);
    return json(403, { ok: false, error: 'FORBIDDEN' }, origin);
  }

  // No profiles row and a non-admin role are the same outcome: FORBIDDEN,
  // never treated as admin. See src/lib/auth.js's getProfile for the same
  // rule applied on the read side.
  if (profile?.role !== 'admin') {
    return json(403, { ok: false, error: 'FORBIDDEN' }, origin);
  }

  const allowedTypes = Object.keys(ALLOWED_CONTENT_TYPES);
  if (!allowedTypes.includes(contentType)) {
    return json(415, { ok: false, error: 'UNSUPPORTED_TYPE', allowed: allowedTypes }, origin);
  }

  const maxUploadBytes = readMaxUploadBytes();
  if (byteSize > maxUploadBytes) {
    return json(413, { ok: false, error: 'FILE_TOO_LARGE', maxBytes: maxUploadBytes }, origin);
  }

  const endpoint = Deno.env.get('S3_ENDPOINT');
  const region = Deno.env.get('S3_REGION');
  const bucket = Deno.env.get('S3_BUCKET');
  const accessKeyId = Deno.env.get('S3_ACCESS_KEY_ID');
  const secretAccessKey = Deno.env.get('S3_SECRET_ACCESS_KEY');

  // Fail closed. An unconfigured S3 target must never silently become an
  // unsigned (or unusable) URL — every one of these is required to sign
  // anything at all.
  if (!endpoint || !region || !bucket || !accessKeyId || !secretAccessKey) {
    console.error('sign-upload: S3 configuration is incomplete; refusing to sign');
    return json(500, { ok: false, error: 'STORAGE_NOT_CONFIGURED' }, origin);
  }

  const storagePath = generateStoragePath(contentType);

  const url = await presignPut({
    endpoint,
    region,
    bucket,
    accessKeyId,
    secretAccessKey,
    key: storagePath,
    contentType,
    expiresIn: PRESIGN_EXPIRES_IN_SECONDS,
  });

  return json(200, { ok: true, url, storagePath }, origin);
});
